<?php
$X = 8;
echo $X++ ."<br>";
echo $X;
//logical operator
//1.&& operatoe
//2.|| operator
//3.! not operator
//4.x or operator
 $x = 5;
 if($x >8 && $x<10){  //
    echo "this is right";
 }else{
    echo "this is wrong";
 }
echo "<br>";
 $x = 6;
 if($x >8 || $x<10){  //
    echo "this is right";
 }else{
    echo "this is wrong";
 }
echo "<br>";
 $s = 7;
 if(!($s>8)){// not operator 
    echo "wrong";
 }else{
    echo "right";
 }



?>
<br>
<?php
$x ="hello";
$x.="every one";
echo $x;


?>
<?php
//space ship operators
$x = 5;
$y = 10;
echo $x<=>$y;


?>